# Read the Docs configuration file

version: 2

build:
  apt_packages:
  - "libclang-14-dev"
  os: "ubuntu-lts-latest"
  tools:
    python: "3"
  jobs:
    post_install:
      - python -m pip install --upgrade --no-cache-dir clang==14.0.6

formats: "all"

python:
  install:
  - requirements: "src/docs/requirements.txt"

sphinx:
  configuration: "src/docs/conf.py"
