# Read the Docs configuration file

version: 2

build:
  apt_packages:
  - "clang"
  os: "ubuntu-lts-latest"
  tools:
    python: "3"

formats: "all"

python:
  install:
  - requirements: "src/docs/requirements.txt"

sphinx:
  configuration: "src/docs/conf.py"
