# Read the Docs configuration file

version: 2

build:
  apt_packages:
  - "clang"
  os: "ubuntu-22.04"
  tools:
    python: "3"

formats: "all"

python:
  install:
  - requirements: "src/docs/requirements.txt"
  system_packages: true

sphinx:
  configuration: "src/docs/conf.py"
