name: "Continuous Integration"

on:
  pull_request:
  push:
    branches-ignore: ["pr/**"]
    tags: ["**"]
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

jobs:
  ci-linux:
    name: Linux CI
    uses: bus1/cabuild/.github/workflows/ci-c-util.yml@v1
    with:
      cabuild_ref: "v1"
      linux: true
      m32: true
      matrixmode: true
      valgrind: true
  ci-macos:
    name: MacOS CI
    uses: bus1/cabuild/.github/workflows/ci-c-util.yml@v1
    with:
      cabuild_ref: "v1"
      linux: false
      macos: true
#
# Windows CI is disabled, as it constantly causes headaches and no-one
# takes care of them. If you need c-stdaux on Windows, feel free to help out.
#
#  ci-windows:
#    name: Windows CI
#    uses: bus1/cabuild/.github/workflows/ci-c-util.yml@v1
#    with:
#      cabuild_ref: "v1"
#      linux: false
#      windows: true
#
  ci-docs:
    name: Documentation CI
    uses: bus1/cabuild/.github/workflows/ci-sphinx.yml@v1
    with:
      source: "./src/docs"
