name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  ci:
    name: CI with Default Configuration
    uses: bus1/cabuild/.github/workflows/ci-c-util.yml@main
    with:
      cabuild_ref: "main"
      m32: true
      matrixmode: true
      valgrind: true
